### ISSUE TITLE
Not getting good results segmenting the tutorial CT data

### ISSUE THREAD

**Issue by paulzyliu** [ACRF-Image-X-Institute/MRI_DistortionQA#73]
I don't think the math is quite right here.. I will try to fix.. I want to add an iterative approach anyway

`marker_size_lower_tol=0.9, marker_size_upper_tol=1`

`        # Set up min and max marker volumes based on expected number of markers`
`        n_voxels_median = np.median(np.array(n_voxels))`
`        voxel_min = (1-self._marker_size_lower_tol) * n_voxels_median`
`        voxel_max = (1+self._marker_size_upper_tol) * n_voxels_median`

This code is currently giving this for the CT data:

Median marker volume: 748.0
Expected marker volume: 74.79999999999998 to 1496.0

(Too many markers found at the moment)

**Comment by bwheelz36** [comment]
Although that is admittedly a wide range, I still get quite a good result using the default parameters:

![image](https://user-images.githubusercontent.com/64300337/170421997-3c98d71e-95db-4db2-ba91-a599239d0c60.png)

```python
from MRI_DistortionQA.MarkerAnalysis import MarkerVolume
from pathlib import Path
'''
download example data and unzip:
https://cloudstor.aarnet.edu.au/plus/s/Wm9vndV47u941JU
'''
data_loc = Path('C:\\Users\\Brendan\\Downloads\\MRI_distortion_QA_sample_data(2)\\MRI_distortion_QA_sample_data\\')
marker_volume = MarkerVolume(data_loc / 'CT', verbose=True)
marker_volume.plot_3D_markers()  # produce a quick plot of marker positions
```

**Comment by paulzyliu** [comment]
This is what I got too but I was looking at those extra markers on the sides... did you use the radius filter to get rid of them? The phantom isn't centered on 0, so would that affect how the radius is applied?

**Comment by bwheelz36** [comment]
yeah to get rid of those you can do
```python
gt_vol = MarkerVolume(gt_data,r_max=300)
```

But it's also a pretty specific problem - hopefully people in general will be better at centering their phantom than we were!
