### ISSUE TITLE
Auto export to slicer

### ISSUE THREAD

**Issue by paulzyliu** [ACRF-Image-X-Institute/MRI_DistortionQA#75]
At the moment, the code automatically exports to slicer (makes the slicer_centroids.mrk.json file and overwrites the old one) each time the segmentation is run.

I think this should be a user run function? Like run the segmentation, then if it looks right, export to slicer? You could overwrite a 'correct' segmentation with a wrong one if you're playing around with the parameters

**Comment by bwheelz36** [comment]
hmm ok I'll switch it back, I just found that I was saving that file nearly every time anyway
